version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 024239493672.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t appcalpy .
      - echo Tagging the Docker image...
      - docker tag appcalpy:latest 024239493672.dkr.ecr.ap-south-1.amazonaws.com/appcalpy
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 024239493672.dkr.ecr.ap-south-1.amazonaws.com/appcalpy
      - echo Creating imagedefinitions.json file for ECS deployment...
      - echo '[{"name":"appcalpy","imageUri":"024239493672.dkr.ecr.ap-south-1.amazonaws.com/appcalpy"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
